-- EGB320 Search and Rescue Robot Control Script for CoppeliaSim (2026)
-- Maze/wall/post/victim generation is done entirely from Python (warehousebot_lib.py) via
-- the ZeroMQ remote API - this script only resolves the robot handle and keeps a small set
-- of optional legacy (2025 warehouse challenge) helper functions available for callScriptFunction.

sim = require('sim')

-- Global variables
local robotHandle
local leftMotor, rightMotor
local dummyCollectorHandles = {}
local dummySampleHandles = {}
local obstacleHandles = {}
local object_detector
local itemTemplateHandles = {}
local itemNamesLookup = {"BOWL", "MUG", "BOTTLE", "SOCCER_BALL", "RUBIKS_CUBE", "CEREAL_BOX"}
local warehouseItemHandles = {}
local heldItems = {}


-- Utility function for safe object handle retrieval
function safeGetObjectHandle(name, required)
    local handle = sim.getObject(name, {noError = true})
    if handle == -1 then
        local status = required and "Error" or "Warning"
        print(status .. ": Could not find object '" .. name .. "'")
    end
    return handle
end

function sysCall_init()
    print("Initializing EGB320 search and rescue robot script...")

    -- Resolve the robot handle safely; used by the optional distance-check helper below.
    -- The maze (walls/posts/victims) is generated by warehousebot_lib.py, not by this script.
    robotHandle = safeGetObjectHandle("/Robot", true)

    -- Storage used only by the optional legacy (2025 warehouse challenge) helper functions below
    itemTemplateHandles = {}
    warehouseItemHandles = {}
    heldItems = {}

    print("Robot script initialization complete - system ready for operation")
end

function sysCall_actuation()
    -- Minimal by design: robot motion is driven from Python via SetTargetVelocities(),
    -- which sets joint target velocities directly - no per-step actuation logic is needed here.
end

function sysCall_sensing()
    -- Minimal by design: vision sensor handling (camera/object detector) is driven from
    -- Python via sim.handleVisionSensor() remote API calls - no per-step sensing logic is needed here.
end

function sysCall_cleanup()
    print("Cleaning up robot script...")
end

-- Generic distance measurement helper (still used by warehousebot_lib.py-style callers)
getDistanceToObject = function(inInts, inFloats, inStrings, inBuffer)
    local results = {}
    local distanceData = {}
    
    if #inInts == 0 then
        print("Warning: getDistanceToObject called with no target objects")
        return {1}, {}, {}, ''
    end
    
    for i = 1, #inInts do
        local threshold = inFloats[i] or 1.0 -- Default threshold if not provided
        local result, data, handles = sim.checkDistance(robotHandle, inInts[i], threshold)
        
        -- Convert to consistent error code format (0 = success, 1 = failure)
        if result == 1 then 
            result = 0
        else
            result = 1
        end
        
        table.insert(results, result)
        
        -- Safely append distance data
        if data then
            for j = 1, #data do
                table.insert(distanceData, data[j])
            end
        end
    end
    
    return results, distanceData, {}, ''
end

-- Legacy (2025 warehouse challenge) object detection helper; unused in the search and rescue phase
getObjectsInView = function(inInts, inFloats, inStrings, inBuffer)
    if object_detector == nil or object_detector == -1 then
        print("Error: Object detector not available")
        return {}, {}, {}, ''
    end
    
    local trigger, packet1, packet2 = sim.handleVisionSensor(object_detector)
    
    if packet2 then
        return packet2, {}, {}, ''
    else
        print("Warning: No vision sensor data available")
        return {}, {}, {}, ''
    end
end

-- Legacy (2025 warehouse challenge) bay content helper; unused in the search and rescue phase
SetBayContents = function(inInts, inFloats, inStrings, inBuffer)
    if #inInts < 4 then
        print("Error: SetBayContents requires 4 integer parameters")
        return {1}, {}, {}, ''
    end
    
    local shelf = inInts[1]
    local bayX = inInts[2]
    local bayY = inInts[3]
    local itemTypeEnum = inInts[4]
    
    -- Validate input parameters
    if itemTypeEnum < 1 or itemTypeEnum > #itemNamesLookup then
        print("Error: Invalid item type enum: " .. itemTypeEnum)
        return {1}, {}, {}, ''
    end
    
    if itemTemplateHandles[itemTypeEnum] == -1 then
        print("Error: Template for item type " .. itemNamesLookup[itemTypeEnum] .. " not available")
        return {1}, {}, {}, ''
    end
    
    -- Get bay handle
    local bayPath = "/Shelf" .. shelf .. "/Bay" .. bayX .. bayY
    local bayHandle = sim.getObject(bayPath, {noError = true})
    
    if bayHandle == -1 then
        print("Error: Could not find bay at " .. bayPath)
        return {1}, {}, {}, ''
    end
    
    -- Create or find item
    local itemName = itemNamesLookup[itemTypeEnum] .. shelf .. bayX .. bayY
    local itemHandle = sim.getObject("/" .. itemName, {noError = true})
    
    if itemHandle == -1 then
        local templateHandle = itemTemplateHandles[itemTypeEnum]
        itemHandle = sim.copyPasteObjects({templateHandle}, 0)[1]
        sim.setObjectAlias(itemHandle, itemName)
        print("Created new item: " .. itemName)
    else
        print("Using existing item: " .. itemName)
    end
    
    -- Position item in bay
    __setObjectPosition__(itemHandle, bayHandle, {0, 0, 0})
    table.insert(warehouseItemHandles, itemHandle)
    
    print("Item " .. itemNamesLookup[itemTypeEnum] .. " placed in bay " .. shelf .. "-" .. bayX .. "-" .. bayY)
    return {0}, {}, {}, ''
end

-- Legacy (2025 warehouse challenge) item collection helper; unused in the search and rescue phase
JoinRobotAndItem = function(inInts, inFloats, inStrings, inBuffer)
    if #inInts == 0 then
        print("Warning: JoinRobotAndItem called with no items")
        return {0}, {}, {}, ''
    end
    
    if #dummySampleHandles == 0 then
        print("Error: No sample dummy handles available")
        return {1}, {}, {}, ''
    end
    
    local itemsGrabbed = 0
    for i = 1, #inInts do
        local objectHandle = inInts[i]
        
        -- Validate object handle
        if objectHandle ~= -1 and sim.isHandle(objectHandle) then
            __setObjectPosition__(objectHandle, dummySampleHandles[1], {0, 0, 0.03})
            sim.setObjectParent(objectHandle, dummySampleHandles[1], true)
            table.insert(heldItems, objectHandle)
            itemsGrabbed = itemsGrabbed + 1
            print("Grabbed item with handle: " .. objectHandle)
        else
            print("Warning: Invalid object handle: " .. objectHandle)
        end
    end
    
    print("Robot grabbed " .. itemsGrabbed .. " items")
    return {0}, {}, {}, ''
end

-- Item release function - still called by warehousebot_lib.py's UpdateItem() via callScriptFunction
RobotReleaseItem = function(inInts, inFloats, inStrings, inBuffer)
    if #heldItems == 0 then
        print("Warning: No items to release")
        return {0}, {}, {}, ''
    end
    
    local objectHandle = table.remove(heldItems, 1)
    
    if objectHandle ~= -1 and sim.isHandle(objectHandle) then
        sim.setObjectParent(objectHandle, -1, true)
        sim.setObjectInt32Param(objectHandle, 3004, 1) -- make object respondable
        sim.setObjectInt32Param(objectHandle, sim.shapeintparam_static, 0)
        print("Released item with handle: " .. objectHandle)
        print("Items remaining in robot: " .. #heldItems)
    else
        print("Error: Invalid item handle during release")
    end
    
    return {0}, {}, {}, ''
end

-- Legacy (2025 warehouse challenge) status helper; unused in the search and rescue phase
GetRobotStatus = function(inInts, inFloats, inStrings, inBuffer)
    local status = {
        #heldItems,                    -- Number of items held
        #warehouseItemHandles,         -- Total items in warehouse
        (leftMotor ~= nil and leftMotor ~= -1) and 1 or 0,  -- Left motor status
        (rightMotor ~= nil and rightMotor ~= -1) and 1 or 0, -- Right motor status
        (object_detector ~= nil and object_detector ~= -1) and 1 or 0 -- Object detector status
    }
    
    return status, {}, {}, ''
end

print("EGB320 search and rescue robot script loaded successfully")
